language: python

install: skip

# if: tag IS present

script:
  - python3 ./test/Application.py

deploy:
  provider: pypi
  user: "__token__"
  password: $PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true
